# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f979e5bee5a84cd1fdd14db32045bb77a00ec8abd65937fb72c8b5c213dc2240f751d512261f5df87da64ce3073e95966c2b3494e2b1753c718121de79e7145

test:
  secret_key_base: 5b96e2ad4d46381e4458c7e4a4cb29d6551e2635117e07b3bef94a15b288fde67612b995de845a584dfcb02e064eb98d3035720e7524f920c717cd217ad32517

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
